// Code generated by mdatagen. DO NOT EDIT.

package hiveauthextension

import "testing"

func TestCheckNoImports(t *testing.T) {
	// This function is intentionally empty as it's generated by mdatagen
}