// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("hiveauth")
	ScopeName = "github.com/graphql-hive/opentelemetry-collector-contrib/extension/hiveauthextension"
)

const (
	ExtensionStability = component.StabilityLevelBeta
)
